EXTRAFLAGS += -flto        # Link time optimization
OLED_DRIVER_ENABLE = yes   # Enables the use of OLED displays
ENCODER_ENABLE = yes       # Enables the use of one or more encoders
RGBLIGHT_ENABLE = yes      # Enable keyboard RGB underglow
LEADER_ENABLE = yes        # Enable the Leader Key feature
MOUSEKEY_ENABLE = yes
TAP_DANCE_ENABLE = yes	   # Enable the Tab Dance feature
COMMAND_ENABLE   = no 	   # Commands for debug and configuration
UNICODE_ENABLE   = no	   # Unicode